# Generated by Django 4.1.7 on 2023-06-23 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_comment_comment_blog_commen_created_0e6ed4_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="body",
            field=models.TextField(default="nil"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="blog.post",
            ),
        ),
    ]
